# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # choose which services to tag and pass as an argument to the providers registry
    # sms
    App\NotificationPublisher\Infrastructure\Services\SMS\Providers\:
        resource: '../src/NotificationPublisher/Infrastructure/Services/SMS/Providers/'
        tags: ['app.sms.providers']

    App\NotificationPublisher\Infrastructure\Services\SMS\SMSProvidersRegistry:
        arguments:
            $smsProviders: !tagged_iterator app.sms.providers

    # emails
    App\NotificationPublisher\Infrastructure\Services\Email\Providers\:
        resource: '../src/NotificationPublisher/Infrastructure/Services/Email/Providers/'
        tags: ['app.email.providers']
    App\NotificationPublisher\Infrastructure\Services\Email\EmailProvidersRegistry:
        arguments:
            $emailProviders: !tagged_iterator app.email.providers

    # pushes
    App\NotificationPublisher\Infrastructure\Services\Push\Providers\:
        resource: '../src/NotificationPublisher/Infrastructure/Services/Push/Providers/'
        tags: [ 'app.push.providers']
    App\NotificationPublisher\Infrastructure\Services\Push\PushProvidersRegistry:
        arguments:
            $pushProviders: !tagged_iterator app.push.providers